### ISSUE TITLE
Green Assessment POST errors

### ISSUE THREAD

**Issue by fablet** [GreenBuildingRegistry/seed#5]
Through Swagger: If any data is input to 'body' field, attempting to POST a new Green Assessment results in either
400 "JSON parse error - No JSON object could be decoded"
or
415 "Unsupported media type \"application/json\" in request" - if JSONParser is removed from parser_classes.

Through RESTClient: The same errors occur when POSTing if the wrong data format is given to validity_duration instead of returning a validation error (which is returned in Swagger if body is left blank).

Leaving validity_duration out of the JSON body, or blank in Swagger, allows the object to save but sets validity_duration to null.

**Comment by fablet** [comment]
When I try to add data to "body" field via PUT or PATCH in Swagger I get: RawPostDataException You cannot access body after reading from request's data stream.

I saw the same error once through RESTClient, but have not been able to reproduce it there since.  Also I have since discovered parse errors through RESTClient reported above were caused by user error.

**Comment by tallus** [comment]
fixed in : https://github.com/GreenBuildingRegistry/seed/pull/8
